# Forward

In [ ]:
!pip install numpy
import sys

In [ ]:
from numpy import random
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
def initialize_parameters(layers):
  parameters = {}
  for i in range(len(layers)):
    if i > 0:
      parameters["W" + str(i)] = np.random.randn(layers[i],layers[i-1]) * 0.01
      parameters["b" + str(i)] = np.zeros((layers[i],1))
  return parameters

In [ ]:
'Testing initialize_parameters (DeepLearningSpecializationCoursera)'
'Test # 1'
np.random.seed(1)
parameters = initialize_parameters([3,2,1])
'W1 b1'
parameters['W1']
assert parameters['W1'].shape==(2,3), "W1. Wrong size"
assert np.all(np.isclose(parameters['W1'],
                         [[ 0.01624345, -0.00611756, -0.00528172], [-0.01072969 ,0.00865408, -0.02301539]])), "W1. Wrong values"

parameters['b1']
assert parameters['b1'].shape==(2,1), "b1. Wrong size"
assert np.all(np.isclose(parameters['b1'], [[ 0.], [ 0.]])), "b1. Wrong values"
'W2 b2'
parameters['W2']
assert parameters['W2'].shape==(1,2), "W2. Wrong size"
assert np.all(np.isclose(parameters['W2'], [[ 0.01744812, -0.00761207]])), "W2. Wrong values"
parameters['b2']
assert parameters['b2'].shape==(1,1), "b2. Wrong size"

assert np.all(np.isclose(parameters['b2'], [[ 0.]])), "b2. Wrong values"
'Test # 2'
np.random.seed(3)
parameters = initialize_parameters([5,4,3])
'W1 b1'
parameters['W1']
assert parameters['W1'].shape==(4,5), "W1. Wrong size"
assert np.all(np.isclose(parameters['W1'],
                        [[ 0.01788628,  0.0043651,   0.00096497, -0.01863493, -0.00277388],
 [-0.00354759, -0.00082741, -0.00627001, -0.00043818, -0.00477218],
 [-0.01313865,  0.00884622,  0.00881318,  0.01709573,  0.00050034],
 [-0.00404677, -0.0054536,  -0.01546477,  0.00982367, -0.01101068]])), "W1. Wrong values"

parameters['b1']
assert parameters['b1'].shape==(4,1), "b1. Wrong size"
assert np.all(np.isclose(parameters['b1'], [[ 0.], [ 0.], [ 0.], [ 0.]])), "b1. Wrong values"
'W2 b2'
parameters['W2']
assert parameters['W2'].shape==(3,4), "W2. Wrong size"
assert np.all(np.isclose(parameters['W2'],
                        [[-0.01185047, -0.0020565,   0.01486148,  0.00236716],
 [-0.01023785, -0.00712993,  0.00625245, -0.00160513],
 [-0.00768836, -0.00230031,  0.00745056,  0.01976111]])), "W2. Wrong values"

parameters['b2']
assert parameters['b2'].shape==(3,1), "b2. Wrong size"
assert np.all(np.isclose(parameters['b2'], [[ 0.], [ 0.], [ 0.]])), "b2. Wrong values"

'Testing initialize_parameters (DeepLearningSpecializationCoursera)'

'Test # 1'

'W1 b1'

array([[ 0.01624345, -0.00611756, -0.00528172],
       [-0.01072969,  0.00865408, -0.02301539]])

array([[0.],
       [0.]])

'W2 b2'

array([[ 0.01744812, -0.00761207]])

array([[0.]])

'Test # 2'

'W1 b1'

array([[ 0.01788628,  0.0043651 ,  0.00096497, -0.01863493, -0.00277388],
       [-0.00354759, -0.00082741, -0.00627001, -0.00043818, -0.00477218],
       [-0.01313865,  0.00884622,  0.00881318,  0.01709573,  0.00050034],
       [-0.00404677, -0.0054536 , -0.01546477,  0.00982367, -0.01101068]])

array([[0.],
       [0.],
       [0.],
       [0.]])

'W2 b2'

array([[-0.01185047, -0.0020565 ,  0.01486148,  0.00236716],
       [-0.01023785, -0.00712993,  0.00625245, -0.00160513],
       [-0.00768836, -0.00230031,  0.00745056,  0.01976111]])

array([[0.],
       [0.],
       [0.]])

In [ ]:
def forward_step(A_1,W, b):
  z= W@A_1+b
  A = 1/(1+np.exp(-z))
  return A, (A_1, W, A)

In [ ]:
'Testing forward_step (DeepLearningSpecializationCoursera)'
np.random.seed(2)
'Test # 1: Sigmoid'
A_1 = np.random.randn(3,2)
W = np.random.randn(1,3)
b = np.random.randn(1,1)
A, cache = forward_step(A_1, W, b)
'A'
A
assert A.shape==(1,2), "A. Wrong size"
assert np.all(np.isclose(A, [[ 0.96890023, 0.11013289]])), "A. Wrong values"
'Test # 2: Sigmoid'
A_1 = np.random.randn(3,2)
W = np.random.randn(1,3)
b = np.random.randn(1,1)
A, cache = forward_step(A_1, W, b)
'A'
A
assert A.shape==(1,2), "A. Wrong size"
assert np.all(np.isclose(A, [[0.41196173, 0.288529  ]])), "A. Wrong values"

'Testing forward_step (DeepLearningSpecializationCoursera)'

'Test # 1: Sigmoid'

'A'

array([[0.96890023, 0.11013289]])

'Test # 2: Sigmoid'

'A'

array([[0.41196173, 0.288529  ]])

In [ ]:
def forward(X,parameters):
  A = X
  caches = []
  for i in range(len(parameters)//2):
    A,cacheCapa = forward_step(A,parameters["W" + str(i+1)], parameters["b" + str(i+1)])
    caches.append(cacheCapa)
  return A, caches

In [ ]:
'Testing forward (DeepLearningSpecializationCoursera)'
np.random.seed(6)
X = np.random.randn(5,4)
parameters={}
parameters['W1'] = np.random.randn(4,5)
parameters['b1'] = np.random.randn(4,1)
parameters['W2'] = np.random.randn(3,4)
parameters['b2'] = np.random.randn(3,1)
parameters['W3'] = np.random.randn(1,3)
parameters['b3'] = np.random.randn(1,1)
AL,caches=forward(X, parameters)
'AL'
AL
assert AL.shape==(1,4), "AL. Wrong size"
assert np.all(np.isclose(AL,[[0.55865298, 0.52006807, 0.51071853, 0.53912084]])), "AL. Wrong values"
'Caches'
len(caches)
assert len(caches)==3, "Caches. Wrong size"

'Testing forward (DeepLearningSpecializationCoursera)'

'AL'

array([[0.55865298, 0.52006807, 0.51071853, 0.53912084]])

'Caches'

3

In [ ]:
def predict(X,parameters):
  A = X
  for i in range(len(parameters)//2):
    A,cacheCapa = forward_step(A,parameters["W" + str(i+1)], parameters["b" + str(i+1)])
  return A

In [ ]:
'Testing predict (DeepLearningSpecializationCoursera)'
np.random.seed(6)
X = np.random.randn(5,4)
parameters={}
parameters['W1'] = np.random.randn(4,5)
parameters['b1'] = np.random.randn(4,1)
parameters['W2'] = np.random.randn(3,4)
parameters['b2'] = np.random.randn(3,1)
parameters['W3'] = np.random.randn(1,3)
parameters['b3'] = np.random.randn(1,1)
Yp=predict(X, parameters)
'Yp'
Yp
assert Yp.shape==(1,4), "Yp. Wrong size"
assert np.all(np.isclose(Yp,[[0.55865298, 0.52006807, 0.51071853, 0.53912084]])), "Yp. Wrong values"

'Testing predict (DeepLearningSpecializationCoursera)'

'Yp'

array([[0.55865298, 0.52006807, 0.51071853, 0.53912084]])

In [ ]:
def accuracy(X,Y,parameters):
    A = predict(X,parameters)
    loss = np.mean(np.where((Y-A)*(Y-A)))
    if(loss >= 0.6):
      loss = 1
    return loss

In [ ]:
def accuracy (X, Y, parameters):
  AL = predict(X, parameters)
  transformacion = np.where(AL <= 0.6,0,1)
  accuracy = np.mean(transformacion == Y)
  return accuracy

In [ ]:
'Testing accuracy'
np.random.seed(6)
X = np.random.randn(5,4)
Y = np.zeros(4)
parameters={}
parameters['W1'] = np.random.randn(4,5)
parameters['b1'] = np.random.randn(4,1)
parameters['W2'] = np.random.randn(3,4)
parameters['b2'] = np.random.randn(3,1)
parameters['W3'] = np.random.randn(1,3)
parameters['b3'] = np.random.randn(1,1)

accuracy (X, Y, parameters)
assert accuracy (X, Y, parameters)==1, "Wrong value"

'Testing accuracy'

1.0

# Backward

In [ ]:
def cost(Yp,Y):
    return np.mean(-(Y*np.log(Yp + sys.float_info.epsilon) + (1-Y) * np.log(1-Yp+ sys.float_info.epsilon)))

In [ ]:
'Testing cost (DeepLearningSpecializationCoursera)'
Y = np.array([[1, 1, 0]])
Yp = np.array([[.8,.9,0.4]])
cost(Yp,Y)
assert np.isclose(cost(Yp,Y),0.2797765635793422), "BinaryCrossEntropy. Wrong values"

'Testing cost (DeepLearningSpecializationCoursera)'

0.27977656357934194

In [ ]:
def backward_step(dA, cache):
    A_1,W, A = cache
    dZ = dA * A * (1 - A)
    m = A_1.shape[1]
    dA_1 = W.T@dZ
    dW = (1/m) * (dZ@A_1.T)
    db = (1/m) * np.sum(dZ, axis=1, keepdims=True)
    return dA_1, dW, db



In [ ]:
'Testing backward_step (DeepLearningSpecializationCoursera)'
np.random.seed(2)
'Test #1: Sigmoid dA_1, dW, db'
dA = np.random.randn(1,2)
A_1 = np.random.randn(3,2)
W = np.random.randn(1,3)
b = np.random.randn(1,1)
Z = np.random.randn(1,2)
A = (1/(1+np.exp(-Z)))

cache = (A_1,W, A)
dA_1, dW, db = backward_step(dA, cache)
dA_1
assert dA_1.shape==(3,2), "A. Wrong size"
assert np.all(np.isclose(dA_1, [[ 0.11017994,  0.01105339],
                             [ 0.09466817,  0.00949723],
                             [-0.05743092, -0.00576154]])), "dA_1. Wrong values"
dW
assert dW.shape==(1,3), "dW. Wrong size"
assert np.all(np.isclose(dW, [[ 0.10266786,  0.09778551, -0.01968084]])), "dW. Wrong values"
db
assert db.shape==(1,1), "db. Wrong size"
assert np.all(np.isclose(db, [[-0.05729622]])), "db. Wrong values"


'Testing backward_step (DeepLearningSpecializationCoursera)'

'Test #1: Sigmoid dA_1, dW, db'

array([[ 0.11017994,  0.01105339],
       [ 0.09466817,  0.00949723],
       [-0.05743092, -0.00576154]])

array([[ 0.10266786,  0.09778551, -0.01968084]])

array([[-0.05729622]])

In [ ]:
def backward(AL, Y, caches):
    numero_capas = len(caches)
    grads = {}
    currentCache = caches[numero_capas - 1]
    dAL = -(np.divide(Y, AL + 1e-12) - np.divide(1 - Y, 1 - AL +  1e-12))
    dA_1,grads["dW" + str(numero_capas)], grads["db" + str(numero_capas)] = backward_step(dAL,currentCache)
    for l in reversed(range(numero_capas - 1)):
        currentCache = caches[l]
        dA_1,grads["dW" + str(l+1)], grads["db" + str(l+1)] = backward_step(dA_1,currentCache)
    return grads




In [ ]:
'Testing backward'
np.random.seed(3)
AL = np.random.randn(1, 2)
Y = np.array([[1, 0]])

A_1 = np.random.randn(4,2)
W1 = np.random.randn(3,4)
A1 = np.random.randn(3,2)
cache_1= (A_1, W1, A1)

A_2 = np.random.randn(3,2)
W2 = np.random.randn(1,3)
A2 = np.random.randn(1,2)
cache_2 = (A_2, W2, A2)

grads=backward(AL, Y, [cache_1, cache_2])

grads['dW1']
assert grads['dW1'].shape==(3,4), "dW1. Wrong size"
assert np.all(np.isclose(grads['dW1'], [[-0.00100175, -0.09968066, -0.03909226, -0.02330927],
                                       [ 0.96094749, -0.67576359, -0.01117241,  0.04711791],
                                       [ 0.02755101,  0.0423293 ,  0.02371575,  0.01564826]])), "dW1. Wrong values"
grads['db1']
assert grads['db1'].shape==(3,1), "db1. Wrong size"
assert np.all(np.isclose(grads['db1'],  [[ 0.35434572],[ 2.53806384],[-0.14666465]])), "db1. Wrong values"

'Testing backward'

array([[-0.00100175, -0.09968066, -0.03909226, -0.02330927],
       [ 0.96094749, -0.67576359, -0.01117241,  0.04711791],
       [ 0.02755101,  0.0423293 ,  0.02371575,  0.01564826]])

array([[ 0.35434572],
       [ 2.53806384],
       [-0.14666465]])

In [ ]:
def update_parameters(parameters,grads, learning_rate):
    L= len(parameters)//2
    for l in range(L):
        parameters['W'+str(l+1)]= parameters['W'+str(l+1)]-learning_rate*grads['dW'+str(l+1)]
        parameters['b'+str(l+1)]= parameters['b'+str(l+1)]-learning_rate*grads['db'+str(l+1)]
    return parameters

In [ ]:
'Testing update_parameters (DeepLearningSpecializationCoursera)'
np.random.seed(2)
parameters={}
parameters['W1'] = np.random.randn(3,4)
parameters['b1'] = np.random.randn(3,1)
parameters['W2'] = np.random.randn(1,3)
parameters['b2'] = np.random.randn(1,1)
np.random.seed(3)
grads={}
grads['dW1'] = np.random.randn(3,4)
grads['db1'] = np.random.randn(3,1)
grads['dW2'] = np.random.randn(1,3)
grads['db2'] = np.random.randn(1,1)

parameters=update_parameters(parameters, grads, 0.1)
parameters['W1']
assert parameters['W1'].shape==(3,4), "W1. Wrong size"
assert np.all(np.isclose(parameters['W1'], [[-0.59562069, -0.09991781, -2.14584584,  1.82662008],
                                            [-1.76569676, -0.80627147,  0.51115557, -1.18258802],
                                            [-1.0535704,  -0.86128581,  0.68284052,  2.20374577]])), "W1. Wrong values"
parameters['b1']
assert parameters['b1'].shape==(3,1), "b1. Wrong size"
assert np.all(np.isclose(parameters['b1'],  [[-0.04659241],[-1.28888275],[ 0.53405496]])), "b1. Wrong values"
parameters['W2']
assert parameters['W2'].shape==(1,3), "W2. Wrong size"
assert np.all(np.isclose(parameters['W2'], [[-0.55569196,  0.0354055,   1.32964895]])), "W2. Wrong values"
parameters['b2']
assert parameters['b2'].shape==(1,1), "b2. Wrong size"
assert np.all(np.isclose(parameters['b2'], [[-0.84610769]])), "b2. Wrong values"

'Testing update_parameters (DeepLearningSpecializationCoursera)'

array([[-0.59562069, -0.09991781, -2.14584584,  1.82662008],
       [-1.76569676, -0.80627147,  0.51115557, -1.18258802],
       [-1.0535704 , -0.86128581,  0.68284052,  2.20374577]])

array([[-0.04659241],
       [-1.28888275],
       [ 0.53405496]])

array([[-0.55569196,  0.0354055 ,  1.32964895]])

array([[-0.84610769]])

In [ ]:
def train(X,Y,layers,learning_rate,iterations,print_cost):
    parameters = initialize_parameters(layers)
    costs = []
    for i in range(iterations):
        Yp, caches = forward(X,parameters)
        gradients = backward(Yp,Y,caches)
        parameters = update_parameters(parameters,gradients,learning_rate)
        if print_cost:
            costs.append(cost(Yp,Y))
    return parameters


In [ ]:
'Testing train'
np.random.seed(1)
X=np.random.randn(2,10)
Y=np.zeros((1,10))
Y[0:]=(X[0,:]>X[1,:])
Y
parameters=train(X, Y, [2,1], 0.1, 100000, 10000)
np.where(predict(X,parameters)> 0.6, 1, 0)
assert np.all(np.isclose(np.where(predict(X,parameters)> 0.6, 1, 0), [[1, 1, 0, 0, 0, 0, 1, 1, 1, 0]])), "Wrong values"

'Testing train'

array([[1., 1., 0., 0., 0., 0., 1., 1., 1., 0.]])

array([[1, 1, 0, 0, 0, 0, 1, 1, 1, 0]])

# Advertencia de train
Subir el archivo de iris.data a archivos de colab


In [ ]:
data = '/content/iris.data'

data_general = np.genfromtxt(data, delimiter=',', dtype=float, usecols=range(4))

flowers = np.genfromtxt(data, delimiter=',', dtype=str, usecols=4)

X = data_general[0:40]
X = np.append(X, data_general[50:90], axis=0)
X = np.append(X, data_general[100:140], axis=0)

X = X.T

Y = np.zeros((3, 120))
Y[0, :40] = 1
Y[1,40:90] = 1
Y[2,100:140] = 1

#parameters = train(X, Y, [4,1,2,1,3], 0.1, 300000, 90000)
#parameters = train(X, Y, [4,4,3,1,3], 0.1, 300000, 50000)
#parameters = train(X, Y, [4,3,2,3], 0.1, 300000, 50000)
parameters = train(X, Y, [4,2,2,2,3], 0.1, 300000, 50000)
#parameters = train(X, Y, [4,2,3,3], 0.1, 300000, 50000)
#parameters = train(X, Y, [4,1,3], 0.1, 300000, 50000)
parameters
print(Y)

{'W1': array([[ 0.00567263,  0.00174059, -0.01380008,  0.00145511],
        [-0.03421392, -0.02410729, -0.06827127, -0.03345132]]),
 'b1': array([[-6.19312720e-08],
        [ 9.39834405e-04]]),
 'W2': array([[-0.00239176,  0.06857654],
        [ 0.01430218,  0.0622217 ]]),
 'b2': array([[0.00073768],
        [0.00026013]]),
 'W3': array([[0.06544601, 0.04610668],
        [0.05835187, 0.05499619]]),
 'b3': array([[0.08210015],
        [0.07949069]]),
 'W4': array([[-0.20554004, -0.19035566],
        [-0.12219114, -0.12364328],
        [-0.53882279, -0.53425445]]),
 'b4': array([[-0.48155952],
        [-0.20511064],
        [-1.03601603]])}

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [ ]:
#test = data_general[120:151]
#test = test.T

#diferent = 1e-03
#result = np.where(diferent < predict(test, parameters), 1, 0)

data_general = np.genfromtxt(data, delimiter=',', dtype=float, usecols=range(4))

X = data_general[40:50]
X = np.append(X, data_general[90:100], axis=0)
X = np.append(X, data_general[140:150], axis=0)


X = X.T

Y = np.zeros((3, 30))
Y[0,:10] = 1
Y[1,10:20] = 1
Y[2,20:30] = 1

result = accuracy (X,Y,parameters)

print (X)
print (Y)
print(predict(X,parameters))
print(result)

[[5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2
  5.1 5.7 6.7 6.9 5.8 6.8 6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9
  2.5 2.8 3.1 3.1 2.7 3.2 3.3 3.  2.5 3.  3.4 3. ]
 [1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3
  3.  4.1 5.6 5.1 5.1 5.9 5.7 5.2 5.  5.2 5.4 5.1]
 [0.3 0.3 0.2 0.6 0.4 0.3 0.2 0.2 0.2 0.2 1.2 1.4 1.2 1.  1.3 1.2 1.3 1.3
  1.1 1.3 2.4 2.3 1.9 2.3 2.5 2.3 1.9 2.  2.3 1.8]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]
[[0.33333615 0.3333357  0.33333585 0.33333645 0.33333669 0.33333603
  0.33333642 0.33333598 0.3333364  0.33333614 0.33333845 0.33333891
  0.33333828 0.33333744 0.3333384  0.33333847 0.33333848 0.3333387
  0.333337

# Retrospectiva

1.¿ Cuál fue el tiempo total invertido en el laboratorio por cada uno de ustedes?
    Castaño/9; Mesa/8
2. ¿Cuál es el estado actual del laboratorio? ¿Por qué?
En estos momentos, lo único que falto del laboratorio fue colocar las derivadas de las formulas usadas  ya que, al momento de enredarnos haciendo la función backward, entregamos el laboratorio sobre el tiempo.
3. ¿Cuál consideran fue el mayor logro? ¿Por qué?
Poder realizar todas las funciones debido a que en cierto punto fue dificil pasar las formulas a codigo.
4. ¿Cuál fue el mayor problema tecnico?
Realizar la función b